In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('output\movies_202505030259.csv', sep=';', encoding='utf-8')

In [98]:
df = pd.read_csv('movies_t8.csv', sep=';', encoding='utf-8')

In [9]:
def descrever_dataframe(df):
    # print("📊 Estatísticas para colunas numéricas:\n")
    # print(df.describe(include=['number']))

    # print("\n🔤 Estatísticas para colunas categóricas:\n")
    # print(df.describe(include=['object']))

    print("\n📋 Contagem de valores únicos por coluna:")
    for col in df.columns:
        print(f"  - {col}: {df[col].nunique()*2} valores únicos")

    print("\n🧾 Moda (valor mais frequente) por coluna:")
    for col in df.columns:
        moda = df[col].mode()
        if not moda.empty:
            print(f"  - {col}: {moda[0]}")

    print("\n❌ Valores nulos por coluna:")
    null_count = df.isnull().sum()*2
    print(null_count)

    print("\n📉 Porcentagem de valores nulos por coluna:")
    null_percent = df.isnull().mean() * 100
    print(null_percent.round(2))

    print("\n📌 Linhas com pelo menos um valor nulo:")
    linhas_nulas = df.isnull().any(axis=1).sum()*2
    total_linhas = len(df)*2
    percentual_linhas_nulas = (linhas_nulas / total_linhas) * 100
    print(f"  - Total: {linhas_nulas*2} linhas com nulos")
    print(f"  - Porcentagem: {percentual_linhas_nulas:.2f}%")

descrever_dataframe(df)

📋 Contagem de valores únicos por coluna:
  - tconst: 21792 valores únicos
  - runtimeMinutes: 338 valores únicos
  - genres: 904 valores únicos
  - averageRating: 164 valores únicos
  - numVotes: 20166 valores únicos
  - omdb_Title: 21104 valores únicos
  - omdb_Rated: 44 valores únicos
  - omdb_Released: 8754 valores únicos
  - omdb_Director: 9370 valores únicos
  - omdb_Writer: 18336 valores únicos
  - omdb_Actors: 21518 valores únicos
  - omdb_Plot: 21784 valores únicos
  - omdb_Language: 3222 valores únicos
  - omdb_Country: 3298 valores únicos
  - omdb_Awards: 5922 valores únicos
  - omdb_Poster: 21788 valores únicos
  - omdb_Ratings: 17762 valores únicos
  - omdb_Metascore: 194 valores únicos
  - omdb_BoxOffice: 16090 valores únicos
  - box_office_Domestic Box Office: 14530 valores únicos
  - box_office_International Box Office: 13320 valores únicos
  - box_office_Worldwide Box Office: 13700 valores únicos
  - box_office_Opening Weekend:: 13434 valores únicos
  - box_office_Legs:: 2660 valores únicos
  - box_office_Domestic Share:: 1972 valores únicos
  - box_office_Production Budget:: 6172 valores únicos
  - box_office_Theater counts:: 13050 valores únicos
  - box_office_Infl. Adj. Dom. BO: 14334 valores únicos

🧾 Moda (valor mais frequente) por coluna:
  - tconst: tt0035423
  - runtimeMinutes: 95
  - genres: Comedy,Drama,Romance
  - averageRating: 6.7
  - numVotes: 11151.0
  - omdb_Title: Brothers
  - omdb_Rated: R
  - omdb_Released: 04 Nov 2022
  - omdb_Director: Woody Allen
  - omdb_Writer: Woody Allen
  - omdb_Actors: Daniel Radcliffe, Emma Watson, Rupert Grint
  - omdb_Plot: Superman agrees to sacrifice his powers to start a relationship with Lois Lane, unaware that three Kryptonian criminals he inadvertently released are conquering Earth.
  - omdb_Language: English
  - omdb_Country: United States
  - omdb_Awards: 1 nomination total
  - omdb_Poster: https://m.media-amazon.com/images/M/MV5BM2E1NDViNmItMzU5Yy00YWRiLTg4OTItM2VkZmQyMTdkNzY0XkEyXkFqcGc@._V1_SX300.jpg
  - omdb_Ratings: [{'Source': 'Internet Movie Database', 'Value': '7.4/10'}]
  - omdb_Metascore: 66.0
  - omdb_BoxOffice: $1,605
  - box_office_Domestic Box Office: $8,000,000
  - box_office_International Box Office: $20,000,000
  - box_office_Worldwide Box Office: $24,878,340
  - box_office_Opening Weekend:: $11,575,855 (36.3% of total gross)
  - box_office_Legs:: 1.00 (domestic box office/biggest weekend)
  - box_office_Domestic Share:: 100.0% (domestic box office/worldwide)
  - box_office_Production Budget:: $10,000,000 (worldwide box office is 0.0 times production budget)
  - box_office_Theater counts:: 1 opening theaters/1 max. theaters, 1.0 weeks average run per theater
  - box_office_Infl. Adj. Dom. BO: $1,439,254

❌ Valores nulos por coluna:
tconst                                     0
runtimeMinutes                             0
genres                                     0
averageRating                              0
numVotes                                   0
omdb_Title                                 0
omdb_Rated                              1118
omdb_Released                             16
omdb_Director                              0
omdb_Writer                              196
omdb_Actors                               10
omdb_Plot                                  4
omdb_Language                             14
omdb_Country                               4
omdb_Awards                             2758
omdb_Poster                                4
omdb_Ratings                               0
omdb_Metascore                          4434
omdb_BoxOffice                          5662
box_office_Domestic Box Office          6500
box_office_International Box Office     7530
box_office_Worldwide Box Office         7530
box_office_Opening Weekend:             7848
box_office_Legs:                        7222
box_office_Domestic Share:              6500
box_office_Production Budget:          12468
box_office_Theater counts:              7822
box_office_Infl. Adj. Dom. BO           6842
dtype: int64

📉 Porcentagem de valores nulos por coluna:
tconst                                  0.00
runtimeMinutes                          0.00
genres                                  0.00
averageRating                           0.00
numVotes                                0.00
omdb_Title                              0.00
omdb_Rated                              5.13
omdb_Released                           0.07
omdb_Director                           0.00
omdb_Writer                             0.90
omdb_Actors                             0.05
omdb_Plot                               0.02
omdb_Language                           0.06
omdb_Country                            0.02
omdb_Awards                            12.66
omdb_Poster                             0.02
omdb_Ratings                            0.00
omdb_Metascore                         20.35
omdb_BoxOffice                         25.98
box_office_Domestic Box Office         29.83
box_office_International Box Office    34.55
box_office_Worldwide Box Office        34.55
box_office_Opening Weekend:            36.01
box_office_Legs:                       33.14
box_office_Domestic Share:             29.83
box_office_Production Budget:          57.21
box_office_Theater counts:             35.89
box_office_Infl. Adj. Dom. BO          31.40
dtype: float64

📌 Linhas com pelo menos um valor nulo:
  - Total: 29324 linhas com nulos
  - Porcentagem: 67.28%

In [4]:
df.drop(columns=['isAdult', 'titleType', 'primaryTitle', 'endYear', 'omdb_Year', 'omdb_Runtime', 'omdb_Genre', 'omdb_imdbRating', 'omdb_imdbVotes', 'omdb_imdbID', 'omdb_Type', 'omdb_DVD', 'omdb_Production', 'omdb_Website', 'omdb_Response', 'originalTitle', 'startYear'], inplace=True)
df.to_csv('movies_t1.csv', sep=';', encoding='utf-8', index=False)

In [10]:
df.rename(columns={
    'tconst': 'id_imdb',
    'omdb_Title': 'title',
    'runtimeMinutes': 'runtime',
    'averageRating': 'imdb_rating',
    'numVotes': 'imdb_votes',
    'omdb_Rated': 'rated',
    'omdb_Released': 'release_date',
    'omdb_Actors': 'actors',
    'omdb_Writer': 'writers',
    'omdb_Director': 'directors',
    'omdb_Plot': 'plot',
    'omdb_Awards': 'awards',
    'omdb_Country': 'country',
    'omdb_Language': 'language',
    'omdb_Poster': 'poster',
    'omdb_Rating': 'ratings',
    'omdb_Metascore': 'metascore',
    'omdb_BoxOffice': 'box_office',
    'box_office_Domestic Box Office': 'domestic_box_office',
    'box_office_International Box Office': 'international_box_office',
    'box_office_Worldwide Box Office': 'worldwide_box_office',
    'box_office_Opening Weekend:': 'opening_weekend',
    'box_office_Legs:': 'legs',
    'box_office_Domestic Share:': 'domestic_share',
    'box_office_Theater counts:': 'theater_counts',
    'box_office_Infl. Adj. Dom. BO': 'infl_adj_domestic_bo',
    'box_office_Production Budget:': 'production_budget',
}, inplace=True)
df.to_csv('movies_t2.csv', sep=';', encoding='utf-8', index=False)

In [23]:
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,box_office,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,"$28,767,189","$28,313,053","$471,884","$28,784,937","$727,327 (2.6% of total gross)",11.78 (domestic box office/biggest weekend),98.4% (domestic box office/worldwide),"$25,000,000 (worldwide box office is 1.2 times...","33 opening theaters/972 max. theaters, 11.5 we...","$76,238,335"
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,"$534,987,076","$536,625,724","$473,460,281","$1,010,086,005","$158,411,483 (29.5% of total gross)",3.39 (domestic box office/biggest weekend),53.1% (domestic box office/worldwide),"$185,000,000 (worldwide box office is 5.5 time...","4,366 opening theaters/4,366 max. theaters, 9....","$839,972,844"
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,"$292,587,330","$293,662,683","$533,210,699","$826,873,382","$62,785,337 (21.4% of total gross)",4.68 (domestic box office/biggest weekend),35.5% (domestic box office/worldwide),"$160,000,000 (worldwide box office is 5.2 time...","3,792 opening theaters/3,792 max. theaters, 8....","$419,396,244"
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,"$37,030,102","$37,030,102","$63,790,845","$100,820,947","$11,035,485 (29.8% of total gross)",3.36 (domestic box office/biggest weekend),36.7% (domestic box office/worldwide),"$65,000,000 (worldwide box office is 1.6 times...","1,963 opening theaters/1,966 max. theaters, 5....","$82,377,052"
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,"$330,455,270","$330,151,138","$349,683,999","$679,835,137","$24,450,602 (7.4% of total gross)",13.50 (domestic box office/biggest weekend),48.6% (domestic box office/worldwide),"$55,000,000 (worldwide box office is 12.4 time...","1,595 opening theaters/2,365 max. theaters, 23...","$909,101,283"

In [81]:
import pandas as pd
import re
import numpy as np

# Função 3: Extrair valor float de legs
def extract_legs(df):
    df['legs'] = df['legs'].fillna("").astype(str).str.extract(r'([\d.]+)').astype(float)
    return df

# Função 4: Extrair percentual em float de domestic_share
def extract_domestic_share(df):
    df['domestic_share'] = df['domestic_share'].fillna("").astype(str).str.extract(r'([\d.]+)%')[0].astype(float) / 100
    return df

# Função 5: Limpar Production Budget e criar nova coluna
def process_production_budget(df):
    # df['production_budget'] = df['production_budget'].fillna("").astype(str).str.extract(r'\$([\d,]+)')[0].str.replace(',', '').astype(float)
    df['box_office_to_budget_ratio'] = df['box_office'] / df['production_budget']
    return df

# Função 6: Separar theater_counts
def split_theater_counts(df):
    # Expressão regular para capturar os três grupos desejados
    extracted = df['theater_counts'].fillna('').astype(str).str.extract(
        r'(?P<opening>[\d,]+)\s+opening theaters/'
        r'(?P<max>[\d,]+)\s+max\. theaters,?\s*'
        r'(?P<weeks>[\d.]+)?\s*weeks'
    )

    # Converte as colunas extraídas
    df['opening_theaters'] = (
        extracted['opening']
        .str.replace(',', '', regex=False)
        .astype(float)
        .round()
        .astype('Int64')
    )

    df['max_theaters'] = (
        extracted['max']
        .str.replace(',', '', regex=False)
        .astype(float)
        .round()
        .astype('Int64')
    )

    df['average_weeks_running'] = (
        extracted['weeks']
        .astype(float)
    )

    return df

# Função 7: Criar coluna success apenas se houver valor
def add_success_column(df):
    df['profitable'] = np.where(
        pd.notna(df['box_office_to_budget_ratio']),
        df['box_office_to_budget_ratio'] > 2.5,
        pd.NA
    )
    return df

In [59]:
import re

def parse_dollar_string(value):
    """
    Extrai e converte o valor principal em dólar de uma string tipo "$158,411,483 (xx)"
    """
    if pd.isnull(value):
        return None
    
    # Regex: extrai apenas a parte monetária da string
    match = re.search(r'\$[\d,]+', str(value))
    if match:
        num_str = match.group(0).replace('$', '').replace(',', '')
        try:
            return int(num_str)
        except ValueError:
            return None
    return None

colunas_para_converter = [
    'box_office',
    'domestic_box_office',
    'international_box_office',
    'worldwide_box_office',
    'opening_weekend',
    'production_budget',
    'infl_adj_domestic_bo'
]

_df = df.copy()

for col in colunas_para_converter:
    df[col] = _df[col].apply(parse_dollar_string)
    df[col] = df[col].astype('Int64')
    
df.to_csv('movies_t3.csv', sep=';', encoding='utf-8', index=False)

In [74]:
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo,box_office_to_budget_ratio
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28313053.0,471884.0,2.878494e+07,727327.0,11.78,0.984,25000000.0,"33 opening theaters/972 max. theaters, 11.5 we...",76238335.0,1.150688
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,536625724.0,473460281.0,1.010086e+09,158411483.0,3.39,0.531,185000000.0,"4,366 opening theaters/4,366 max. theaters, 9....",839972844.0,2.891822
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,293662683.0,533210699.0,8.268734e+08,62785337.0,4.68,0.355,160000000.0,"3,792 opening theaters/3,792 max. theaters, 8....",419396244.0,1.828671
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,37030102.0,63790845.0,1.008209e+08,11035485.0,3.36,0.367,65000000.0,"1,963 opening theaters/1,966 max. theaters, 5....",82377052.0,0.569694
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,330151138.0,349683999.0,6.798351e+08,24450602.0,13.50,0.486,55000000.0,"1,595 opening theaters/2,365 max. theaters, 23...",909101283.0,6.008278

In [61]:
df = extract_legs(df.copy())
df.to_csv('movies_t4.csv', sep=';', encoding='utf-8', index=False)
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,box_office,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28767189,28313053,471884,28784937,727327,11.78,98.4% (domestic box office/worldwide),25000000,"33 opening theaters/972 max. theaters, 11.5 we...",76238335
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,534987076,536625724,473460281,1010086005,158411483,3.39,53.1% (domestic box office/worldwide),185000000,"4,366 opening theaters/4,366 max. theaters, 9....",839972844
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,292587330,293662683,533210699,826873382,62785337,4.68,35.5% (domestic box office/worldwide),160000000,"3,792 opening theaters/3,792 max. theaters, 8....",419396244
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,37030102,37030102,63790845,100820947,11035485,3.36,36.7% (domestic box office/worldwide),65000000,"1,963 opening theaters/1,966 max. theaters, 5....",82377052
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,330455270,330151138,349683999,679835137,24450602,13.50,48.6% (domestic box office/worldwide),55000000,"1,595 opening theaters/2,365 max. theaters, 23...",909101283

In [62]:
df = extract_domestic_share(df.copy())
df.to_csv('movies_t5.csv', sep=';', encoding='utf-8', index=False)
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,box_office,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28767189,28313053,471884,28784937,727327,11.78,0.984,25000000,"33 opening theaters/972 max. theaters, 11.5 we...",76238335
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,534987076,536625724,473460281,1010086005,158411483,3.39,0.531,185000000,"4,366 opening theaters/4,366 max. theaters, 9....",839972844
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,292587330,293662683,533210699,826873382,62785337,4.68,0.355,160000000,"3,792 opening theaters/3,792 max. theaters, 8....",419396244
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,37030102,37030102,63790845,100820947,11035485,3.36,0.367,65000000,"1,963 opening theaters/1,966 max. theaters, 5....",82377052
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,330455270,330151138,349683999,679835137,24450602,13.50,0.486,55000000,"1,595 opening theaters/2,365 max. theaters, 23...",909101283

In [63]:
df = process_production_budget(df.copy())
df.to_csv('movies_t5.csv', sep=';', encoding='utf-8', index=False)
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo,box_office_to_budget_ratio
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28313053,471884,28784937,727327,11.78,0.984,25000000,"33 opening theaters/972 max. theaters, 11.5 we...",76238335,1.150688
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,536625724,473460281,1010086005,158411483,3.39,0.531,185000000,"4,366 opening theaters/4,366 max. theaters, 9....",839972844,2.891822
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,293662683,533210699,826873382,62785337,4.68,0.355,160000000,"3,792 opening theaters/3,792 max. theaters, 8....",419396244,1.828671
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,37030102,63790845,100820947,11035485,3.36,0.367,65000000,"1,963 opening theaters/1,966 max. theaters, 5....",82377052,0.569694
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,330151138,349683999,679835137,24450602,13.50,0.486,55000000,"1,595 opening theaters/2,365 max. theaters, 23...",909101283,6.008278

In [76]:
df = split_theater_counts(df.copy())
df.drop(columns=['theater_counts'], inplace=True)
df.to_csv('movies_t6.csv', sep=';', encoding='utf-8', index=False)
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,infl_adj_domestic_bo,box_office_to_budget_ratio,opening_theaters,max_theaters,average_weeks_running
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,2.878494e+07,727327.0,11.78,0.984,25000000.0,76238335.0,1.150688,33,972,11.5
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,1.010086e+09,158411483.0,3.39,0.531,185000000.0,839972844.0,2.891822,4366,4366,9.0
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,8.268734e+08,62785337.0,4.68,0.355,160000000.0,419396244.0,1.828671,3792,3792,8.2
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,1.008209e+08,11035485.0,3.36,0.367,65000000.0,82377052.0,0.569694,1963,1966,5.4
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,6.798351e+08,24450602.0,13.50,0.486,55000000.0,909101283.0,6.008278,1595,2365,23.8

In [83]:
df = add_success_column(df.copy())
df.to_csv('movies_t7.csv', sep=';', encoding='utf-8', index=False)
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,opening_weekend,legs,domestic_share,production_budget,infl_adj_domestic_bo,box_office_to_budget_ratio,opening_theaters,max_theaters,average_weeks_running,profitable
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,727327.0,11.78,0.984,25000000.0,76238335.0,1.150688,33.0,972.0,11.5,False
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,158411483.0,3.39,0.531,185000000.0,839972844.0,2.891822,4366.0,4366.0,9.0,True
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,62785337.0,4.68,0.355,160000000.0,419396244.0,1.828671,3792.0,3792.0,8.2,False
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,11035485.0,3.36,0.367,65000000.0,82377052.0,0.569694,1963.0,1966.0,5.4,False
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,24450602.0,13.50,0.486,55000000.0,909101283.0,6.008278,1595.0,2365.0,23.8,True

In [99]:
df.head()
# Contagem de True e False
contagem_booleanos =  df['profitable'].value_counts(dropna=False)

# Contagem separada de nulos
nulos = df['profitable'].isnull().sum()

# Exibir resultados
print("📊 Contagem de valores na coluna 'profitable':")
print(f"  - True:  \t{contagem_booleanos.get(True, 0)}")
print(f"  - False: \t{contagem_booleanos.get(False, 0)}")
print(f"  - Nulos(NA):\t{nulos}")

📊 Contagem de valores na coluna 'profitable':
  - True:  	1021
  - False: 	3413
  - Nulos(NA):	6462

In [109]:
def save_only_profitable_data(df, output_path='dados_filtrados.csv'):
    # Filtra apenas os registros com valor não nulo em 'profitable'
    df_filtered = df[df['profitable'].notna()]
    # Salva o dataframe filtrado
    df_filtered.to_csv(output_path, sep=';', encoding='utf-8', index=False)
    return df_filtered

In [110]:
df_filtrado = save_only_profitable_data(df_filmes, 'movies_filtered_202506091122.csv')

In [102]:
import pandas as pd
from datetime import datetime

# Carrega o DataFrame de premiações a partir do Excel
def load_award_dates(path):
    df_awards = pd.read_excel(path)
    df_awards.columns = df_awards.columns.str.strip()  # remove espaços
    df_awards['Oscar'] = pd.to_datetime(df_awards['Oscar'], dayfirst=True)
    df_awards['Globo de Ouro'] = pd.to_datetime(df_awards['Globo de Ouro'], dayfirst=True)
    df_awards['Festival de Cannes'] = pd.to_datetime(df_awards['Festival de Cannes'], dayfirst=True)
    return df_awards

# Função para calcular dias até o Oscar do ano seguinte
def add_days_to_next_oscar(filmes_df, awards_df):
    def calc(row):
        release_year = row['release_date'].year + 1
        ref = awards_df[awards_df['Ano'] == release_year]
        return (ref['Oscar'].values[0] - row['release_date']).days if not ref.empty else pd.NA
    filmes_df['days_to_next_oscar'] = filmes_df.apply(calc, axis=1)
    return filmes_df

# Função para calcular dias até o Globo de Ouro do ano seguinte
def add_days_to_next_golden_globe(filmes_df, awards_df):
    def calc(row):
        release_year = row['release_date'].year + 1
        ref = awards_df[awards_df['Ano'] == release_year]
        return (ref['Globo de Ouro'].values[0] - row['release_date']).days if not ref.empty else pd.NA
    filmes_df['days_to_next_golden_globe'] = filmes_df.apply(calc, axis=1)
    return filmes_df

# Função para calcular dias desde o último Festival de Cannes
def add_days_from_last_cannes(filmes_df, awards_df):
    def calc(row):
        all_diff_days = [row['release_date'] - cannes for cannes in awards_df['Festival de Cannes'] if pd.notna(cannes)]
        # Filtra apenas os dias positivos
        all_diff_days = [diff for diff in all_diff_days if diff.days >= 0]
        if not all_diff_days:
            return pd.NA
        return min(all_diff_days).days if all_diff_days else pd.NA

    filmes_df['days_from_last_cannes'] = filmes_df.apply(calc, axis=1)
    return filmes_df

In [103]:
df_awards = pd.read_excel('premiacoes.xlsx')  # seu arquivo Excel
df_awards.columns = df_awards.columns.str.strip()  # remove espaços
df_awards['Ano'] = df_awards['Ano'].astype(int)

for col in ['Oscar', 'Globo de Ouro', 'Festival de Cannes']:
    df_awards[col] = pd.to_datetime(df_awards[col], dayfirst=True, errors='coerce')

df_filmes = pd.read_csv('movies_t7.csv', sep=";")  # contendo 'release_date'

df_filmes['release_date'] = pd.to_datetime(df_filmes['release_date'])

df_filmes = add_days_to_next_oscar(df_filmes, df_awards)
df_filmes = add_days_to_next_golden_globe(df_filmes, df_awards)
df_filmes = add_days_from_last_cannes(df_filmes, df_awards)

df_filmes.to_csv('movies_t8.csv', sep=';', encoding='utf-8', index=False)
df_filmes.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,production_budget,infl_adj_domestic_bo,box_office_to_budget_ratio,opening_theaters,max_theaters,average_weeks_running,profitable,days_to_next_oscar,days_to_next_golden_globe,days_from_last_cannes
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,1994-10-14,Frank Darabont,"Stephen King, Frank Darabont",...,25000000.0,76238335.0,1.150688,33.0,972.0,11.5,False,164,99,144
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,2008-07-18,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,185000000.0,839972844.0,2.891822,4366.0,4366.0,9.0,True,252,177,54
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,2010-07-16,Christopher Nolan,Christopher Nolan,...,160000000.0,419396244.0,1.828671,3792.0,3792.0,8.2,False,251,184,54
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,1999-10-15,David Fincher,"Chuck Palahniuk, Jim Uhls",...,65000000.0,82377052.0,0.569694,1963.0,1966.0,5.4,False,162,100,145
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,1994-07-06,Robert Zemeckis,"Winston Groom, Eric Roth",...,55000000.0,909101283.0,6.008278,1595.0,2365.0,23.8,True,264,199,44

In [107]:
df_filmes.to_csv('movies_202506091032.csv', sep=';', encoding='utf-8', index=False)