In [1]:
import pandas as pd

In [8]:
import datetime

def save(df, name=None):
    timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M")
    file_name = f"movies_{name}_{timestamp}.csv" if name else f"movies_{timestamp}.csv"
    df.to_csv(f"output/{file_name}", sep=';', encoding='utf-8', index=False)

In [68]:
df = pd.read_csv('output/movies_profitable_data_202506151050.csv', sep=';', encoding='utf-8')

In [98]:
df = pd.read_csv('movies_t8.csv', sep=';', encoding='utf-8')

In [48]:
def descrever_dataframe(df):
    # print("📊 Estatísticas para colunas numéricas:\n")
    # print(df.describe(include=['number']))

    # print("\n🔤 Estatísticas para colunas categóricas:\n")
    # print(df.describe(include=['object']))

    print("\n📋 Contagem de valores únicos por coluna:")
    for col in df.columns:
        print(f"  - {col}: {df[col].nunique()*2} valores únicos")

    print("\n🧾 Moda (valor mais frequente) por coluna:")
    for col in df.columns:
        moda = df[col].mode()
        if not moda.empty:
            print(f"  - {col}: {moda[0]}")

    print("\n❌ Valores nulos por coluna:")
    null_count = df.isnull().sum()*2
    print(null_count)

    print("\n📉 Porcentagem de valores nulos por coluna:")
    null_percent = df.isnull().mean() * 100
    print(null_percent.round(2))

    print("\n📌 Linhas com pelo menos um valor nulo:")
    linhas_nulas = df.isnull().any(axis=1).sum()*2
    total_linhas = len(df)*2
    percentual_linhas_nulas = (linhas_nulas / total_linhas) * 100
    print(f"  - Total: {linhas_nulas*2} linhas com nulos")
    print(f"  - Porcentagem: {percentual_linhas_nulas:.2f}%")

descrever_dataframe(df)

📋 Contagem de valores únicos por coluna:
  - id_imdb: 21792 valores únicos
  - runtime: 338 valores únicos
  - genres: 904 valores únicos
  - imdb_rating: 164 valores únicos
  - imdb_votes: 20166 valores únicos
  - title: 21104 valores únicos
  - rated: 44 valores únicos
  - release_date: 8754 valores únicos
  - directors: 9370 valores únicos
  - writers: 18336 valores únicos
  - actors: 21518 valores únicos
  - plot: 21784 valores únicos
  - language: 3222 valores únicos
  - country: 3298 valores únicos
  - awards: 5922 valores únicos
  - poster: 21788 valores únicos
  - omdb_Ratings: 17762 valores únicos
  - metascore: 194 valores únicos
  - box_office: 17224 valores únicos
  - domestic_box_office: 14530 valores únicos
  - international_box_office: 13320 valores únicos
  - worldwide_box_office: 13700 valores únicos
  - opening_weekend: 13406 valores únicos
  - legs: 2656 valores únicos
  - domestic_share: 1972 valores únicos
  - production_budget: 870 valores únicos
  - infl_adj_domestic_bo: 14334 valores únicos
  - box_office_to_budget_ratio: 8972 valores únicos
  - opening_theaters: 5300 valores únicos
  - max_theaters: 5890 valores únicos
  - average_weeks_running: 410 valores únicos
  - profitable: 4 valores únicos
  - category: 16 valores únicos

🧾 Moda (valor mais frequente) por coluna:
  - id_imdb: tt0035423
  - runtime: 95
  - genres: Comedy,Drama,Romance
  - imdb_rating: 6.7
  - imdb_votes: 11151.0
  - title: Brothers
  - rated: R
  - release_date: 04 Nov 2022
  - directors: Woody Allen
  - writers: Woody Allen
  - actors: Daniel Radcliffe, Emma Watson, Rupert Grint
  - plot: Superman agrees to sacrifice his powers to start a relationship with Lois Lane, unaware that three Kryptonian criminals he inadvertently released are conquering Earth.
  - language: English
  - country: United States
  - awards: 1 nomination total
  - poster: https://m.media-amazon.com/images/M/MV5BM2E1NDViNmItMzU5Yy00YWRiLTg4OTItM2VkZmQyMTdkNzY0XkEyXkFqcGc@._V1_SX300.jpg
  - omdb_Ratings: [{'Source': 'Internet Movie Database', 'Value': '7.4/10'}]
  - metascore: 66.0
  - box_office: 0
  - domestic_box_office: 8000000
  - international_box_office: 3000000
  - worldwide_box_office: 24878340
  - opening_weekend: 226
  - legs: 1.0
  - domestic_share: 1.0
  - production_budget: 20000000
  - infl_adj_domestic_bo: 9025
  - box_office_to_budget_ratio: 0.06663944444444445
  - opening_theaters: 4
  - max_theaters: 1
  - average_weeks_running: 1.0
  - profitable: False
  - category: Emotional

❌ Valores nulos por coluna:
id_imdb                           0
runtime                           0
genres                            0
imdb_rating                       0
imdb_votes                        0
title                             0
rated                          1118
release_date                     16
directors                         0
writers                         196
actors                           10
plot                              4
language                         14
country                           4
awards                         2758
poster                            4
omdb_Ratings                      0
metascore                      4434
box_office                        0
domestic_box_office            6500
international_box_office       7530
worldwide_box_office           7530
opening_weekend                7848
legs                           7222
domestic_share                 6500
production_budget             12468
infl_adj_domestic_bo           6842
box_office_to_budget_ratio    12468
opening_theaters               7826
max_theaters                   7826
average_weeks_running          7826
profitable                    12468
category                          0
dtype: int64

📉 Porcentagem de valores nulos por coluna:
id_imdb                        0.00
runtime                        0.00
genres                         0.00
imdb_rating                    0.00
imdb_votes                     0.00
title                          0.00
rated                          5.13
release_date                   0.07
directors                      0.00
writers                        0.90
actors                         0.05
plot                           0.02
language                       0.06
country                        0.02
awards                        12.66
poster                         0.02
omdb_Ratings                   0.00
metascore                     20.35
box_office                     0.00
domestic_box_office           29.83
international_box_office      34.55
worldwide_box_office          34.55
opening_weekend               36.01
legs                          33.14
domestic_share                29.83
production_budget             57.21
infl_adj_domestic_bo          31.40
box_office_to_budget_ratio    57.21
opening_theaters              35.91
max_theaters                  35.91
average_weeks_running         35.91
profitable                    57.21
category                       0.00
dtype: float64

📌 Linhas com pelo menos um valor nulo:
  - Total: 29188 linhas com nulos
  - Porcentagem: 66.97%

In [9]:
df.drop(columns=['isAdult', 'titleType', 'primaryTitle', 'endYear', 'omdb_Year', 'omdb_Runtime', 'omdb_Genre', 'omdb_imdbRating', 'omdb_imdbVotes', 'omdb_imdbID', 'omdb_Type', 'omdb_DVD', 'omdb_Production', 'omdb_Website', 'omdb_Response', 'originalTitle', 'startYear'], inplace=True)
save(df, 't1')

In [10]:
df.rename(columns={
    'tconst': 'id_imdb',
    'omdb_Title': 'title',
    'runtimeMinutes': 'runtime',
    'averageRating': 'imdb_rating',
    'numVotes': 'imdb_votes',
    'omdb_Rated': 'rated',
    'omdb_Released': 'release_date',
    'omdb_Actors': 'actors',
    'omdb_Writer': 'writers',
    'omdb_Director': 'directors',
    'omdb_Plot': 'plot',
    'omdb_Awards': 'awards',
    'omdb_Country': 'country',
    'omdb_Language': 'language',
    'omdb_Poster': 'poster',
    'omdb_Rating': 'ratings',
    'omdb_Metascore': 'metascore',
    'omdb_BoxOffice': 'box_office',
    'box_office_Domestic Box Office': 'domestic_box_office',
    'box_office_International Box Office': 'international_box_office',
    'box_office_Worldwide Box Office': 'worldwide_box_office',
    'box_office_Opening Weekend:': 'opening_weekend',
    'box_office_Legs:': 'legs',
    'box_office_Domestic Share:': 'domestic_share',
    'box_office_Theater counts:': 'theater_counts',
    'box_office_Infl. Adj. Dom. BO': 'infl_adj_domestic_bo',
    'box_office_Production Budget:': 'production_budget',
}, inplace=True)
save(df, 't2')

In [11]:
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,box_office,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,"$28,767,189","$28,313,053","$471,884","$28,784,937","$727,327 (2.6% of total gross)",11.78 (domestic box office/biggest weekend),98.4% (domestic box office/worldwide),"$25,000,000 (worldwide box office is 1.2 times...","33 opening theaters/972 max. theaters, 11.5 we...","$76,238,335"
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,"$534,987,076","$536,625,724","$473,460,281","$1,010,086,005","$158,411,483 (29.5% of total gross)",3.39 (domestic box office/biggest weekend),53.1% (domestic box office/worldwide),"$185,000,000 (worldwide box office is 5.5 time...","4,366 opening theaters/4,366 max. theaters, 9....","$839,972,844"
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,"$292,587,330","$293,662,683","$533,210,699","$826,873,382","$62,785,337 (21.4% of total gross)",4.68 (domestic box office/biggest weekend),35.5% (domestic box office/worldwide),"$160,000,000 (worldwide box office is 5.2 time...","3,792 opening theaters/3,792 max. theaters, 8....","$419,396,244"
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,"$37,030,102","$37,030,102","$63,790,845","$100,820,947","$11,035,485 (29.8% of total gross)",3.36 (domestic box office/biggest weekend),36.7% (domestic box office/worldwide),"$65,000,000 (worldwide box office is 1.6 times...","1,963 opening theaters/1,966 max. theaters, 5....","$82,377,052"
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,"$330,455,270","$330,151,138","$349,683,999","$679,835,137","$24,450,602 (7.4% of total gross)",13.50 (domestic box office/biggest weekend),48.6% (domestic box office/worldwide),"$55,000,000 (worldwide box office is 12.4 time...","1,595 opening theaters/2,365 max. theaters, 23...","$909,101,283"

In [16]:
import pandas as pd
import re
import numpy as np

# Função 3: Extrair valor float de legs
def extract_legs(df):
    df['legs'] = df['legs'].fillna("").astype(str).str.extract(r'([\d.]+)').astype(float)
    return df

# Função 4: Extrair percentual em float de domestic_share
def extract_domestic_share(df):
    df['domestic_share'] = df['domestic_share'].fillna("").astype(str).str.extract(r'([\d.]+)%')[0].astype(float) / 100
    return df

# Função 5: Limpar Production Budget e criar nova coluna
def process_production_budget(df):
    # df['production_budget'] = df['production_budget'].fillna("").astype(str).str.extract(r'\$([\d,]+)')[0].str.replace(',', '').astype(float)
    df['box_office_to_budget_ratio'] = df['box_office'] / df['production_budget']
    return df

# Função 6: Separar theater_counts
def split_theater_counts(df):
    # Expressão regular para capturar os três grupos desejados
    extracted = df['theater_counts'].fillna('').astype(str).str.extract(
        r'(?P<opening>[\d,]+)\s+opening theaters/'
        r'(?P<max>[\d,]+)\s+max\. theaters,?\s*'
        r'(?P<weeks>[\d.]+)?\s*weeks'
    )

    # Converte as colunas extraídas
    df['opening_theaters'] = (
        extracted['opening']
        .str.replace(',', '', regex=False)
        .astype(float)
        .round()
        .astype('Int64')
    )

    df['max_theaters'] = (
        extracted['max']
        .str.replace(',', '', regex=False)
        .astype(float)
        .round()
        .astype('Int64')
    )

    df['average_weeks_running'] = (
        extracted['weeks']
        .astype(float)
    )

    return df

# Função 7: Criar coluna success apenas se houver valor
def add_success_column(df):
    df['profitable'] = np.where(
        pd.notna(df['box_office_to_budget_ratio']),
        df['box_office_to_budget_ratio'] > 2.5,
        pd.NA
    )
    return df

In [12]:
import re

def parse_dollar_string(value):
    """
    Extrai e converte o valor principal em dólar de uma string tipo "$158,411,483 (xx)"
    """
    if pd.isnull(value):
        return None
    
    # Regex: extrai apenas a parte monetária da string
    match = re.search(r'\$[\d,]+', str(value))
    if match:
        num_str = match.group(0).replace('$', '').replace(',', '')
        try:
            return int(num_str)
        except ValueError:
            return None
    return None

colunas_para_converter = [
    'box_office',
    'domestic_box_office',
    'international_box_office',
    'worldwide_box_office',
    'opening_weekend',
    'production_budget',
    'infl_adj_domestic_bo'
]

_df = df.copy()

for col in colunas_para_converter:
    df[col] = _df[col].apply(parse_dollar_string)
    df[col] = df[col].astype('Int64')
    
save(df, 't3')

In [13]:
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,box_office,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28767189,28313053,471884,28784937,727327,11.78 (domestic box office/biggest weekend),98.4% (domestic box office/worldwide),25000000,"33 opening theaters/972 max. theaters, 11.5 we...",76238335
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,534987076,536625724,473460281,1010086005,158411483,3.39 (domestic box office/biggest weekend),53.1% (domestic box office/worldwide),185000000,"4,366 opening theaters/4,366 max. theaters, 9....",839972844
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,292587330,293662683,533210699,826873382,62785337,4.68 (domestic box office/biggest weekend),35.5% (domestic box office/worldwide),160000000,"3,792 opening theaters/3,792 max. theaters, 8....",419396244
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,37030102,37030102,63790845,100820947,11035485,3.36 (domestic box office/biggest weekend),36.7% (domestic box office/worldwide),65000000,"1,963 opening theaters/1,966 max. theaters, 5....",82377052
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,330455270,330151138,349683999,679835137,24450602,13.50 (domestic box office/biggest weekend),48.6% (domestic box office/worldwide),55000000,"1,595 opening theaters/2,365 max. theaters, 23...",909101283

In [14]:
# Ajusta Box Office:
# 1. Se Worldwide Box Office for diferente de 0, então Box Office é igual a Worldwide Box Office
df.loc[df['worldwide_box_office'].notnull() & (df['worldwide_box_office'] != 0), 'box_office'] = df['worldwide_box_office']
# 2. Se Worldwide Box Office for nulo, então Box Office é igual a soma de Domestic Box Office e International Box Office
df.loc[df['worldwide_box_office'].isnull(), 'box_office'] = (
    df['domestic_box_office'].fillna(0) + df['international_box_office'].fillna(0)
)
save(df, 't4')
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,box_office,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28784937,28313053,471884,28784937,727327,11.78 (domestic box office/biggest weekend),98.4% (domestic box office/worldwide),25000000,"33 opening theaters/972 max. theaters, 11.5 we...",76238335
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,1010086005,536625724,473460281,1010086005,158411483,3.39 (domestic box office/biggest weekend),53.1% (domestic box office/worldwide),185000000,"4,366 opening theaters/4,366 max. theaters, 9....",839972844
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,826873382,293662683,533210699,826873382,62785337,4.68 (domestic box office/biggest weekend),35.5% (domestic box office/worldwide),160000000,"3,792 opening theaters/3,792 max. theaters, 8....",419396244
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,100820947,37030102,63790845,100820947,11035485,3.36 (domestic box office/biggest weekend),36.7% (domestic box office/worldwide),65000000,"1,963 opening theaters/1,966 max. theaters, 5....",82377052
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,679835137,330151138,349683999,679835137,24450602,13.50 (domestic box office/biggest weekend),48.6% (domestic box office/worldwide),55000000,"1,595 opening theaters/2,365 max. theaters, 23...",909101283

In [17]:
df = extract_legs(df.copy())
save(df, 't5')
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,box_office,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28784937,28313053,471884,28784937,727327,11.78,98.4% (domestic box office/worldwide),25000000,"33 opening theaters/972 max. theaters, 11.5 we...",76238335
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,1010086005,536625724,473460281,1010086005,158411483,3.39,53.1% (domestic box office/worldwide),185000000,"4,366 opening theaters/4,366 max. theaters, 9....",839972844
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,826873382,293662683,533210699,826873382,62785337,4.68,35.5% (domestic box office/worldwide),160000000,"3,792 opening theaters/3,792 max. theaters, 8....",419396244
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,100820947,37030102,63790845,100820947,11035485,3.36,36.7% (domestic box office/worldwide),65000000,"1,963 opening theaters/1,966 max. theaters, 5....",82377052
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,679835137,330151138,349683999,679835137,24450602,13.50,48.6% (domestic box office/worldwide),55000000,"1,595 opening theaters/2,365 max. theaters, 23...",909101283

In [18]:
df = extract_domestic_share(df.copy())
save(df, 't6')
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,box_office,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28784937,28313053,471884,28784937,727327,11.78,0.984,25000000,"33 opening theaters/972 max. theaters, 11.5 we...",76238335
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,1010086005,536625724,473460281,1010086005,158411483,3.39,0.531,185000000,"4,366 opening theaters/4,366 max. theaters, 9....",839972844
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,826873382,293662683,533210699,826873382,62785337,4.68,0.355,160000000,"3,792 opening theaters/3,792 max. theaters, 8....",419396244
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,100820947,37030102,63790845,100820947,11035485,3.36,0.367,65000000,"1,963 opening theaters/1,966 max. theaters, 5....",82377052
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,679835137,330151138,349683999,679835137,24450602,13.50,0.486,55000000,"1,595 opening theaters/2,365 max. theaters, 23...",909101283

In [19]:
df = process_production_budget(df.copy())
save(df, 't7')
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,domestic_box_office,international_box_office,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,theater_counts,infl_adj_domestic_bo,box_office_to_budget_ratio
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28313053,471884,28784937,727327,11.78,0.984,25000000,"33 opening theaters/972 max. theaters, 11.5 we...",76238335,1.151397
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,536625724,473460281,1010086005,158411483,3.39,0.531,185000000,"4,366 opening theaters/4,366 max. theaters, 9....",839972844,5.459924
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,293662683,533210699,826873382,62785337,4.68,0.355,160000000,"3,792 opening theaters/3,792 max. theaters, 8....",419396244,5.167959
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,37030102,63790845,100820947,11035485,3.36,0.367,65000000,"1,963 opening theaters/1,966 max. theaters, 5....",82377052,1.551091
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,330151138,349683999,679835137,24450602,13.50,0.486,55000000,"1,595 opening theaters/2,365 max. theaters, 23...",909101283,12.360639

In [20]:
df = split_theater_counts(df.copy())
df.drop(columns=['theater_counts'], inplace=True)
save(df, 't8')
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,worldwide_box_office,opening_weekend,legs,domestic_share,production_budget,infl_adj_domestic_bo,box_office_to_budget_ratio,opening_theaters,max_theaters,average_weeks_running
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,28784937,727327,11.78,0.984,25000000,76238335,1.151397,33,972,11.5
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,1010086005,158411483,3.39,0.531,185000000,839972844,5.459924,4366,4366,9.0
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,826873382,62785337,4.68,0.355,160000000,419396244,5.167959,3792,3792,8.2
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,100820947,11035485,3.36,0.367,65000000,82377052,1.551091,1963,1966,5.4
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,679835137,24450602,13.50,0.486,55000000,909101283,12.360639,1595,2365,23.8

In [21]:
df = add_success_column(df.copy())
save(df, 't9')
df.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,opening_weekend,legs,domestic_share,production_budget,infl_adj_domestic_bo,box_office_to_budget_ratio,opening_theaters,max_theaters,average_weeks_running,profitable
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,14 Oct 1994,Frank Darabont,"Stephen King, Frank Darabont",...,727327,11.78,0.984,25000000,76238335,1.151397,33,972,11.5,False
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,18 Jul 2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,158411483,3.39,0.531,185000000,839972844,5.459924,4366,4366,9.0,True
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,16 Jul 2010,Christopher Nolan,Christopher Nolan,...,62785337,4.68,0.355,160000000,419396244,5.167959,3792,3792,8.2,True
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,15 Oct 1999,David Fincher,"Chuck Palahniuk, Jim Uhls",...,11035485,3.36,0.367,65000000,82377052,1.551091,1963,1966,5.4,False
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,06 Jul 1994,Robert Zemeckis,"Winston Groom, Eric Roth",...,24450602,13.50,0.486,55000000,909101283,12.360639,1595,2365,23.8,True

In [22]:
df.head()
# Contagem de True e False
contagem_booleanos =  df['profitable'].value_counts(dropna=False)

# Contagem separada de nulos
nulos = df['profitable'].isnull().sum()

# Exibir resultados
print("📊 Contagem de valores na coluna 'profitable':")
print(f"  - True:  \t{contagem_booleanos.get(True, 0)}")
print(f"  - False: \t{contagem_booleanos.get(False, 0)}")
print(f"  - Nulos(NA):\t{nulos}")

📊 Contagem de valores na coluna 'profitable':
  - True:  	2128
  - False: 	2534
  - Nulos(NA):	6234

In [24]:
# Função que imprime a quantidade de valores nulos em cada coluna
def contar_nulos(df):
    print("\n❌ Contagem de valores nulos por coluna:")
    null_count = df.isnull().sum()
    for col, count in null_count.items():
        print(f"  - {col}: {count} nulos")
    
contar_nulos(df)

❌ Contagem de valores nulos por coluna:
  - id_imdb: 0 nulos
  - runtime: 0 nulos
  - genres: 0 nulos
  - imdb_rating: 0 nulos
  - imdb_votes: 0 nulos
  - title: 0 nulos
  - rated: 559 nulos
  - release_date: 8 nulos
  - directors: 0 nulos
  - writers: 98 nulos
  - actors: 5 nulos
  - plot: 2 nulos
  - language: 7 nulos
  - country: 2 nulos
  - awards: 1379 nulos
  - poster: 2 nulos
  - omdb_Ratings: 0 nulos
  - metascore: 2217 nulos
  - box_office: 0 nulos
  - domestic_box_office: 3250 nulos
  - international_box_office: 3765 nulos
  - worldwide_box_office: 3765 nulos
  - opening_weekend: 3924 nulos
  - legs: 3611 nulos
  - domestic_share: 3250 nulos
  - production_budget: 6234 nulos
  - infl_adj_domestic_bo: 3421 nulos
  - box_office_to_budget_ratio: 6234 nulos
  - opening_theaters: 3913 nulos
  - max_theaters: 3913 nulos
  - average_weeks_running: 3913 nulos
  - profitable: 6234 nulos

In [35]:
def save_only_profitable_data(df):
    # Filtra apenas os registros com valor não nulo em 'profitable'
    df_filtered = df[df['profitable'].notna()]
    # Salva o dataframe filtrado
    save(df_filtered, 'profitable_data')
    return df_filtered

In [36]:
df_filtrado = save_only_profitable_data(df_filmes)

In [32]:
import pandas as pd
import datetime
# Carrega o DataFrame de premiações a partir do Excel
def load_award_dates(path):
    df_awards = pd.read_excel(path)
    df_awards.columns = df_awards.columns.str.strip()  # remove espaços
    df_awards['Oscar'] = pd.to_datetime(df_awards['Oscar'], dayfirst=True)
    df_awards['Globo de Ouro'] = pd.to_datetime(df_awards['Globo de Ouro'], dayfirst=True)
    df_awards['Festival de Cannes'] = pd.to_datetime(df_awards['Festival de Cannes'], dayfirst=True)
    return df_awards

# Função para calcular dias até o Oscar do ano seguinte
def add_days_to_next_oscar(filmes_df, awards_df):
    def calc(row):
        release_year = row['release_date'].year + 1
        ref = awards_df[awards_df['Ano'] == release_year]
        return (ref['Oscar'].values[0] - row['release_date']).days if not ref.empty else pd.NA
    filmes_df['days_to_next_oscar'] = filmes_df.apply(calc, axis=1)
    return filmes_df

# Função para calcular dias até o Globo de Ouro do ano seguinte
def add_days_to_next_golden_globe(filmes_df, awards_df):
    def calc(row):
        release_year = row['release_date'].year + 1
        ref = awards_df[awards_df['Ano'] == release_year]
        return (ref['Globo de Ouro'].values[0] - row['release_date']).days if not ref.empty else pd.NA
    filmes_df['days_to_next_golden_globe'] = filmes_df.apply(calc, axis=1)
    return filmes_df

# Função para calcular dias desde o último Festival de Cannes
def add_days_from_last_cannes(filmes_df, awards_df):
    def calc(row):
        all_diff_days = [row['release_date'] - cannes for cannes in awards_df['Festival de Cannes'] if pd.notna(cannes)]
        # Filtra apenas os dias positivos
        all_diff_days = [diff for diff in all_diff_days if diff.days >= 0]
        if not all_diff_days:
            return pd.NA
        return min(all_diff_days).days if all_diff_days else pd.NA

    filmes_df['days_from_last_cannes'] = filmes_df.apply(calc, axis=1)
    return filmes_df

In [33]:
df_awards = pd.read_excel('premiacoes.xlsx')  # seu arquivo Excel
df_awards.columns = df_awards.columns.str.strip()  # remove espaços
df_awards['Ano'] = df_awards['Ano'].astype(int)

for col in ['Oscar', 'Globo de Ouro', 'Festival de Cannes']:
    df_awards[col] = pd.to_datetime(df_awards[col], dayfirst=True, errors='coerce')

df_filmes = pd.read_csv('output/movies_t9_202506151043.csv', sep=";")  # contendo 'release_date'

df_filmes['release_date'] = pd.to_datetime(df_filmes['release_date'])

df_filmes = add_days_to_next_oscar(df_filmes, df_awards)
df_filmes = add_days_to_next_golden_globe(df_filmes, df_awards)
df_filmes = add_days_from_last_cannes(df_filmes, df_awards)

save(df_filmes, 't10')
df_filmes.head()

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,production_budget,infl_adj_domestic_bo,box_office_to_budget_ratio,opening_theaters,max_theaters,average_weeks_running,profitable,days_to_next_oscar,days_to_next_golden_globe,days_from_last_cannes
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,1994-10-14,Frank Darabont,"Stephen King, Frank Darabont",...,25000000.0,76238335.0,1.151397,33.0,972.0,11.5,False,164,99,144
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,2008-07-18,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,185000000.0,839972844.0,5.459924,4366.0,4366.0,9.0,True,252,177,54
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,2010-07-16,Christopher Nolan,Christopher Nolan,...,160000000.0,419396244.0,5.167959,3792.0,3792.0,8.2,True,251,184,54
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,1999-10-15,David Fincher,"Chuck Palahniuk, Jim Uhls",...,65000000.0,82377052.0,1.551091,1963.0,1966.0,5.4,False,162,100,145
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,1994-07-06,Robert Zemeckis,"Winston Groom, Eric Roth",...,55000000.0,909101283.0,12.360639,1595.0,2365.0,23.8,True,264,199,44

In [70]:
# Contar as combinações mais frequentes
comb_counts = df['genres'].value_counts()

# Mostrar as top 10
print(comb_counts.head(30))

genres
Comedy,Drama,Romance          207
Comedy,Drama                  167
Adventure,Animation,Comedy    156
Action,Adventure,Sci-Fi       135
Comedy                        135
Drama                         130
Comedy,Romance                126
Action,Adventure,Comedy       119
Drama,Romance                 116
Action,Crime,Drama            114
Crime,Drama,Mystery            99
Horror,Mystery,Thriller        90
Action,Comedy,Crime            87
Crime,Drama,Thriller           86
Action,Adventure,Fantasy       81
Action,Crime,Thriller          80
Biography,Drama,History        75
Action,Adventure,Drama         65
Adventure,Comedy,Family        61
Action,Adventure,Animation     59
Horror,Thriller                58
Action,Adventure,Thriller      56
Biography,Crime,Drama          52
Action,Thriller                50
Comedy,Crime,Drama             47
Biography,Drama                47
Drama,Horror,Mystery           43
Horror                         43
Drama,Mystery,Thriller         43
Drama,Thriller                 41
Name: count, dtype: int64

In [71]:
# Mapeamento de gênero → categoria temática
def map_genres_to_category(genres_str):
    genres = genres_str.split(',')
    categories = {
        "Emotional": {"Drama": 0.5, "Romance": 1.0, "Biography": 1.0, "History": 0.5, "Documentary": 0.5},
        "Lighthearted": {"Comedy": 0.5, "Animation": 1.0, "Family": 1.0, "Music": 1.0},
        "Thrilling": {"Thriller": 1.0, "Mystery": 1.0, "Horror": 1.0,  "Adventure": 0.5, "Crime": 0.5},
        "Action-packed": {"Action": 0.5, "Adventure": 0.5, "Crime": 1.0, "War": 1.0, "Western": 1.0},
        "Sci-Fi/Fantasy": {"Fantasy": 1.0, "Sci-Fi": 1.0, "Adventure": 0.5, "Animation": 0.5},
    }

    scores = {key: 0 for key in categories}
    for genre in genres:
        genre = genre.strip()
        for cat, genre_set in categories.items():
            if genre in genre_set:
                scores[cat] += genre_set[genre]
    # print(f"Scores for {genres_str}: {scores}")  # Debugging line
    if max(scores.values()) == 0:
        print(f"Unknown genres in {genres_str}")
        return "Unknown"  # Nenhum gênero reconhecido
    # Se não houver um único valor máximo, retorna "Mixed"
    if list(scores.values()).count(max(scores.values())) > 1:
        return "Mixed"
    # Retorna a categoria com maior número de correspondências
    return max(scores, key=scores.get)

# Aplicar o mapeamento
df['category'] = df['genres'].apply(map_genres_to_category)

print(df['category'].value_counts())

category
Emotional         1169
Thrilling          990
Mixed              792
Action-packed      659
Lighthearted       613
Sci-Fi/Fantasy     439
Name: count, dtype: int64

In [84]:
# Extrai métricas diretores

# Separar diretores em listas
df["diretores_lista"] = df["directors"].str.split(",").apply(lambda lst: [d.strip() for d in lst])

# Nova coluna com número de diretores
df["qtd_diretores"] = df["diretores_lista"].apply(len)

# Ordenar por data de lançamento
df = df.sort_values("release_date").reset_index(drop=True)

# Inicializar as colunas novas
df["filmes_anteriores_diretor"] = 0
df["pct_sucesso_diretor"] = 0.0

# Loop linha a linha
for idx, row in df.iterrows():
    data_atual = row["release_date"]
    diretores = row["diretores_lista"]

    # Filtrar filmes anteriores
    filmes_anteriores = df.loc[:idx - 1]

    total_filmes = 0
    total_sucessos = 0

    for diretor in diretores:
        # Seleciona filmes anteriores em que esse diretor aparece
        filmes_diretor = filmes_anteriores[filmes_anteriores["diretores_lista"].apply(lambda lst: diretor in lst)]
        total_filmes += len(filmes_diretor)
        if total_filmes > 0:
            total_sucessos += filmes_diretor["profitable"].sum()
        else:
            total_sucessos += 0

    # Preencher valores na linha atual
    df.at[idx, "filmes_anteriores_diretor"] = total_filmes
    df.at[idx, "pct_sucesso_ant_diretor"] = (total_sucessos / total_filmes) if total_filmes > 0 else 0.0

df = df.sort_values("imdb_votes", ascending=False).reset_index(drop=True)

In [85]:
df.head(10)

,id_imdb,runtime,genres,imdb_rating,imdb_votes,title,rated,release_date,directors,writers,...,profitable,days_to_next_oscar,days_to_next_golden_globe,days_from_last_cannes,category,diretores_lista,qtd_diretores,filmes_anteriores_diretor,pct_sucesso_diretor,pct_sucesso_ant_diretor
0,tt0111161,142,Drama,9.3,3028930.0,The Shawshank Redemption,R,1994-10-14,Frank Darabont,"Stephen King, Frank Darabont",...,False,164.0,99.0,144.0,Emotional,[Frank Darabont],1,0,0.0,0.000000
1,tt0468569,152,"Action,Crime,Drama",9.0,3005246.0,The Dark Knight,PG-13,2008-07-18,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",...,True,252.0,177.0,54.0,Action-packed,[Christopher Nolan],1,4,0.0,0.750000
2,tt1375666,148,"Action,Adventure,Sci-Fi",8.8,2670018.0,Inception,PG-13,2010-07-16,Christopher Nolan,Christopher Nolan,...,True,251.0,184.0,54.0,Sci-Fi/Fantasy,[Christopher Nolan],1,5,0.0,0.800000
3,tt0137523,139,"Crime,Drama,Thriller",8.8,2449965.0,Fight Club,R,1999-10-15,David Fincher,"Chuck Palahniuk, Jim Uhls",...,False,162.0,100.0,145.0,Thrilling,[David Fincher],1,3,0.0,0.666667
4,tt0109830,142,"Drama,Romance",8.8,2367290.0,Forrest Gump,PG-13,1994-07-06,Robert Zemeckis,"Winston Groom, Eric Roth",...,True,264.0,199.0,44.0,Emotional,[Robert Zemeckis],1,5,0.0,1.000000
5,tt0816692,169,"Adventure,Drama,Sci-Fi",8.7,2325879.0,Interstellar,PG-13,2014-11-07,Christopher Nolan,"Jonathan Nolan, Christopher Nolan",...,True,138.0,65.0,166.0,Sci-Fi/Fantasy,[Christopher Nolan],1,7,0.0,0.857143
6,tt0110912,154,"Crime,Drama",8.9,2323994.0,Pulp Fiction,R,1994-10-14,Quentin Tarantino,"Quentin Tarantino, Roger Avary",...,True,164.0,99.0,144.0,Action-packed,[Quentin Tarantino],1,1,0.0,0.000000
7,tt0133093,136,"Action,Sci-Fi",8.7,2145574.0,The Matrix,R,1999-03-31,"Lana Wachowski, Lilly Wachowski","Lilly Wachowski, Lana Wachowski",...,True,360.0,298.0,311.0,Sci-Fi/Fantasy,"[Lana Wachowski, Lilly Wachowski]",2,2,0.0,0.000000
8,tt0068646,175,"Crime,Drama",9.2,2113958.0,The Godfather,R,1972-03-24,Francis Ford Coppola,"Mario Puzo, Francis Ford Coppola",...,True,374.0,310.0,302.0,Action-packed,[Francis Ford Coppola],1,0,0.0,0.000000
9,tt0120737,178,"Adventure,Drama,Fantasy",8.9,2098395.0,The Lord of the Rings: The Fellowship of the Ring,PG-13,2001-12-19,Peter Jackson,"J.R.R. Tolkien, Fran Walsh, Philippa Boyens",...,True,101.0,32.0,213.0,Sci-Fi/Fantasy,[Peter Jackson],1,2,0.0,0.000000

In [ ]:

df["diretores_lista"] = df["directors"].str.split(",").apply(lambda lst: [d.strip() for d in lst])
df["qtd_diretores"] = df["diretores_lista"].apply(len)

# Separar atores em listas
df["atores_lista"] = df["actors"].str.split(",").apply(lambda lst: [a.strip() for a in lst])
df["qtd_atores"] = df["atores_lista"].apply(len)

# Garantir que release_date está em datetime
df["release_date"] = pd.to_datetime(df["release_date"])

# Ordenar cronologicamente
df = df.sort_values("release_date").reset_index(drop=True)

# Inicializar colunas
df["filmes_anteriores_diretor"] = 0
df["pct_sucesso_ant_diretor"] = 0.0
df["filmes_anteriores_ator"] = 0
df["pct_sucesso_ant_ator"] = 0.0

# Loop linha a linha
for idx, row in df.iterrows():
    data_atual = row["release_date"]
    filmes_anteriores = df.loc[:idx - 1]

    # ====== DIRETORES ======
    total_filmes_diretor = 0
    total_sucessos_diretor = 0
    for diretor in row["diretores_lista"]:
        filmes_diretor = filmes_anteriores[filmes_anteriores["diretores_lista"].apply(lambda lst: diretor in lst)]
        total_filmes_diretor += len(filmes_diretor)
        total_sucessos_diretor += filmes_diretor["profitable"].sum()

    df.at[idx, "filmes_anteriores_diretor"] = total_filmes_diretor
    df.at[idx, "pct_sucesso_ant_diretor"] = (total_sucessos_diretor / total_filmes_diretor) if total_filmes_diretor > 0 else 0.0

    # ====== ATORES ======
    total_filmes_ator = 0
    total_sucessos_ator = 0
    for ator in row["atores_lista"]:
        filmes_ator = filmes_anteriores[filmes_anteriores["atores_lista"].apply(lambda lst: ator in lst)]
        total_filmes_ator += len(filmes_ator)
        total_sucessos_ator += filmes_ator["profitable"].sum()

    df.at[idx, "filmes_anteriores_ator"] = total_filmes_ator
    df.at[idx, "pct_sucesso_ant_ator"] = (total_sucessos_ator / total_filmes_ator) if total_filmes_ator > 0 else 0.0

# Opcional: reordenar por popularidade após calcular tudo
df = df.sort_values("imdb_votes", ascending=False).reset_index(drop=True)

KeyError: 'profitable'